### ISSUE TITLE
Добавить мердж объектов внутри коллекций

### ISSUE THREAD

**Issue by paatrofimov** [vostok/configuration#16]
Если есть абстракция

```
IItem {
    A: string;
    B: string;
}

IItemsCollection {
    items: IItem[];
}
```

есть данные в одном `IConfigurationSource `

`{ "items": [ { A: "123" } ] }`

и данные во втором `IConfigurationSource`

`{ "items": [ { B: "456" } ] }`

и я комбинирую эти sources, то хотелось бы иметь возможность получать смердженный объект конфигурации

`{ "items": [ { A: "123", B: "456" } ] }`

**Comment by paatrofimov** [comment]
Абстракции, кажется, случайно, на джаваскрипте написал, но суть должна быть понятна )

**Comment by iloktionov** [comment]
Implemented in https://github.com/vostok/configuration.abstractions/commit/6465318a9adcb4d890ed60a9504f8fa8c9d4dda4 with new `ArrayMergeStyle.PerElement` option.
