### ISSUE TITLE
Возможность установить IConfigurationSource только при отсутствии существующего

### ISSUE THREAD

**Issue by ZarkariaDia** [vostok/configuration#26]
Хочется иметь возможность устанавливать IConfigurationSource только в том случае, если он отсутствует для конкретного вида настроек. Возможно подойдет метод вида `TrySetupSourceFor<TSettings>(source)`, либо сама возможность проверки наличия установленного ConfigurationSource'а через метод `HasSourceFor<TSettings>()`.

Сейчас для вышеуказанной проверки необходимо пытаться получить настройки и при неустановленном ConfigurationSource'е ловить ArgumentException:
```
try
{
    configurationProvider.Get<TSettings>();
}
catch (ArgumentException)
{
    configurationProvider.SetupSourceFor<TSettings>(sourceFactory());
}
```

**Comment by iloktionov** [comment]
Added `HasSourceFor` and `TrySetupSourceFor` methods to the implementation class (`ConfigurationProvider`). Haven't done the same for `IConfigurationProvider` interface yet.
